### ISSUE TITLE
Return channel videos when adding a new channel

### ISSUE THREAD

**Issue by aziz512** [aziz512/youtube-tracker#32]
We currently return just 200 when adding a new channel. It would be nice to fetch and return channel information (videos) so that front end can display the new channel without having to re-fetch data for all the channels (which is network-heavy).
The returned object should have the same format as objects returned in the array from `/videos`

**Comment by Edmond120** [comment]
Sure, I'll add another field to the input json
Ex.
{
    'url": <channel_url>,
    'fetch_channel': true,
}

**Comment by Edmond120** [comment]
Also, if you are to fetch the channel anyways, then we can check if the id is valid without any additional time spent on querying Youtube

**Comment by aziz512** [comment]
I think we should keep it simple and do it every time you add. I wouldn't worry about the overhead for fetching 1 channel's information especially since this will be done once per channel addition. This will also allow us to validate ids in all cases.
